### ISSUE TITLE
traceid and spanid not populated to logging infrastructure

### ISSUE THREAD

**Issue by imod** [netshoes/spring-cloud-sleuth-amqp#11]
Hi,

I added the [spring-cloud-sleuth-amqp-starter](https://github.com/netshoes/spring-cloud-sleuth-amqp-starter) to our project and now I see the info in the rabbit message:

```
Node:         rabbit@localhost
Connection:   127.0.0.1:52941 -> 127.0.0.1:5672
Virtual host: /
User:         guest
Channel:      9
Exchange:     exch.common
Routing keys: [<<"key.event">>]
Queue:        q.event
Properties:   [{<<"priority">>,signedint,0},
               {<<"delivery_mode">>,signedint,2},
               {<<"headers">>,table,
                [{<<"spanTraceId">>,longstr,<<"aadc44f18370946c">>},
                 {<<"spanId">>,longstr,<<"aadc44f18370946c">>},
                 {<<"currentSpan">>,longstr,
                  <<"[Trace: aadc44f18370946c, Span: aadc44f18370946c, Parent: null, exportable:false]">>},
                 {<<"messageSent">>,longstr,<<"true">>},
                 {<<"spanSampled">>,longstr,<<"0">>},
                 {<<"__TypeId__">>,longstr,
                  <<"com.company.MyEvent">>}]},
               {<<"content_encoding">>,longstr,<<"UTF-8">>},
               {<<"content_type">>,longstr,<<"application/json">>}]
Payload: 
{...}
```

But for some reason `traceid` and `spanid` are not populated to our logging statements.
The log4j pattern is configured with the %X and prints the info if available:

`<PatternLayout pattern="%d{HH:mm:ss.SSS} %X [%thread] %-5level %logger{36} - %msg%n" />`

What am I missing?

sorry, maybe I'm not clear enough with my description, what I try to do is this: https://stackoverflow.com/questions/47903493/spring-sleuth-does-not-populate-traceid-and-spanid-to-rabbithandler

**Comment by imod** [comment]
closing this in favor of #13

**Comment by reggie-k** [comment]
I am using the spring-cloud-sleuth-amqp-starter, version 0.10, the trace and span ids are in the message headers, but are not in the log, neither for the rabbitTemplate.sendAndConvert side nor for the @RabbitHandler side. Running on Spring Boot 1.5.10

**Comment by imod** [comment]
@reggie-k did you add it to the log pattern (with `%X`)? This is the pattern we use for log4j2...

```
	<Appenders>
		<Console name="Console" target="SYSTEM_OUT">
			<PatternLayout
				pattern="%d{HH:mm:ss.SSS} [%thread] %X %-5level %logger{36} - %msg %throwable %n" />
		</Console>
	</Appenders>
```

**Comment by reggie-k** [comment]
@imod  I don't think it is related to the log pattern. I do see [MyAppName, , ] preappended to my messages in the log, but the spanId and the traceId are not present. My original app was sending messages from the main class.
On the contrary, when I add a RestController, which now sends the messages, I see that once the controller is invoked, the initial traceId and spanId are created just fine, logged correctly, and furthermore are correctly logged by @RabbitListener.
So the problem is only there when the framework creates the inital traceId and spanId, so it seems. Should I open a new issue for this or is it covered by one of the existing open issues?
Also, I like your framework a lot, it addresses a really important need, and would love to use it with latest versions of spring-sleuth, based on brave, are there any plans to update it?
